Update changes.yml

diff --git a/.github/workflows/changes.yml b/.github/workflows/changes.yml
--- a/.github/workflows/changes.yml
+++ b/.github/workflows/changes.yml
@@ -20,46 +20,51 @@ jobs:
         run: |
           echo ${{ steps.myRequest.outputs.res}}
       
-      - name: Check on failures
-        if: steps.myRequest.outcome == 'success' 
-        run: exit 1 
-         echo ${{steps.myRequest.outcome}}
-       
-      - name: Check on success
-        if: steps.myRequest.outcome != 'success' 
-        run: 
-         echo ${{steps.myRequest.outcome}}
+      - name: Deploy IFlow
+        run: |
+            data=$(curl --request POST --url 'https://980934bbtrial.it-cpitrial06.cfapps.us10-001.hana.ondemand.com/api/v1/DeployIntegrationDesigntimeArtifact?Version=%271.0.5%27&Id=527new_flow%27' --header 'Accept: application/json' --header 'X-CSRF-Token: 5e11af77cdb0917cacfe08d38272600d181134d7bd5c9ca261ab01f9a978b3841683873558258' --header 'DataServiceVersion: 2.0' --header 'APIKey: 6pagSQDAKqCBv9K4sf7vL6GaOikghSbe' -u shivamrajput1710@gmail.com:Shivam@123)
+            echo $data
         
-      - name: Call To Get IFLow Details
-        run: |   
-          curl --request GET \
-          --header 'authorization: Bearer ${{ fromJson(steps.myRequest.outputs.res).access_token }}' \
-          --header 'content-type: application/json' \
-          --url https://content-agent-engine.cfapps.us10.hana.ondemand.com/v1/contentResources?grant_type=client_credentials
+#       - name: Check on failures
+#         if: steps.myRequest.outcome == 'success' 
+#         run: exit 1 
+#          echo ${{steps.myRequest.outcome}}
+       
+#       - name: Check on success
+#         if: steps.myRequest.outcome != 'success' 
+#         run: 
+#          echo ${{steps.myRequest.outcome}}
+        
+#       - name: Call To Get IFLow Details
+#         run: |   
+#           curl --request GET \
+#           --header 'authorization: Bearer ${{ fromJson(steps.myRequest.outputs.res).access_token }}' \
+#           --header 'content-type: application/json' \
+#           --url https://content-agent-engine.cfapps.us10.hana.ondemand.com/v1/contentResources?grant_type=client_credentials
           
-      - name: Get Changed Files
-        id: getfile
-        run: |
-          echo "files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
+#       - name: Get Changed Files
+#         id: getfile
+#         run: |
+#           echo "files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
           
-      - name: Changed File Name
-        run: |
-            echo ${{ steps.getfile.outputs.files }}
+#       - name: Changed File Name
+#         run: |
+#             echo ${{ steps.getfile.outputs.files }}
             
-      - name: Run Docker
-        uses: docker-practice/actions-setup-docker@master
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - run: |
-          REPO=${{ steps.getfile.outputs.files }}
-          DB_NAME="${REPO// /^}"
-          echo $DB_NAME
-          MYPATH=$DB_NAME
-          MYFILE=${MYPATH##*/}
-          MYSAMPLE=${MYFILE%.*}
-          echo $MYSAMPLE
-          REPOS=$MYSAMPLE
-          DBNAME="${REPOS//^/ }"
-          echo $DBNAME
-          docker run -v $PWD:/etc/newman -t postman/newman run "test/$DBNAME.json"
+#       - name: Run Docker
+#         uses: docker-practice/actions-setup-docker@master
+#       - uses: actions/checkout@v3
+#         with:
+#           fetch-depth: 0
+#       - run: |
+#           REPO=${{ steps.getfile.outputs.files }}
+#           DB_NAME="${REPO// /^}"
+#           echo $DB_NAME
+#           MYPATH=$DB_NAME
+#           MYFILE=${MYPATH##*/}
+#           MYSAMPLE=${MYFILE%.*}
+#           echo $MYSAMPLE
+#           REPOS=$MYSAMPLE
+#           DBNAME="${REPOS//^/ }"
+#           echo $DBNAME
+#           docker run -v $PWD:/etc/newman -t postman/newman run "test/$DBNAME.json"
