Update collection.yml

diff --git a/.github/workflows/collection.yml b/.github/workflows/collection.yml
--- a/.github/workflows/collection.yml
+++ b/.github/workflows/collection.yml
@@ -14,7 +14,15 @@ jobs:
     - name: Docker for newma
       id: myRequest
       run: |
-        docker run -v $PWD:/etc/newman -t postman/newman:latest run "./test/new_flow.json"
+         folder_path=$PWD:/etc/newman/Docker/test
+         file_name=new_flow.json
+         if [ -e "$folder_path/$file_name" ]; then
+            echo "File exists!"
+          else
+            echo "File does not exist!"
+            exit 1  # You can exit with a non-zero code to indicate a failure
+          fi
+         docker run -v $PWD:/etc/newman -t postman/newman:latest run "./test/new_flow.json"
       continue-on-error: true
     - name: Check on failures     
       run: 
