Update ctms.yml

diff --git a/.github/workflows/ctms.yml b/.github/workflows/ctms.yml
--- a/.github/workflows/ctms.yml
+++ b/.github/workflows/ctms.yml
@@ -16,10 +16,10 @@ jobs:
  
       - name: Check if token creation succeeded
         run: |
-         if grep -q "unauthorized.*Bad credentials" <<< "$(cat $GITHUB_EVENT_PATH)"; then
-              echo "Token creation failed: Bad credentials or insufficient permissions."
-              exit 1
-            
+         if ! gh auth login --with-token curl --request GET --url "https://development-dn6yj4ti.authentication.ca10.hana.ondemand.com/oauth/token?grant_type=client_credentials" -u "sb-e0a3d792-09fd-4411!b805|cas-uaa-prod!b58:J+neLeyi7wqBcEPXM1hl4CqAkTE=" --header 'content-type: application/json'; then
+            echo "Token creation failed: Bad credentials or insufficient permissions."
+            exit 1
+                
           else
             echo "Token creation done!"
           fi
