Update ctms.yml

diff --git a/.github/workflows/ctms.yml b/.github/workflows/ctms.yml
--- a/.github/workflows/ctms.yml
+++ b/.github/workflows/ctms.yml
@@ -14,11 +14,14 @@ jobs:
         run: |
           echo "res=$(curl --request GET --url "https://development-dn6yj4ti.authentication.ca10.hana.ondemand.com/oauth/token?grant_type=client_credentials" -u "sb-e0a3d792-09fd-47-8a2c-e4213af53411!b805|cas-uaa-prod!b58:J+neLeyi7wqBcEPXM1hl4CqAkTE=" --header 'content-type: application/json')" >> $GITHUB_OUTPUT
  
-      - name: Check on failures  
-        if: ${{ steps.runPostman.outcome != 'success' }}
+      - name: Check if token creation succeeded
         run: |
-          echo 'failedd'
-          exit 1
+          if [ $? -eq 0 ]; then
+            echo "Token creation succeeded!"
+          else
+            echo "Token creation failed!"
+            exit 1
+          fi
       - name: Show Token
         run: |
           echo ${{ steps.myRequest.outputs.res}}
