Update ctms.yml

diff --git a/.github/workflows/ctms.yml b/.github/workflows/ctms.yml
--- a/.github/workflows/ctms.yml
+++ b/.github/workflows/ctms.yml
@@ -13,19 +13,24 @@ jobs:
         id: runPostman
         run: |
           echo "res=$(curl --request GET --url "https://development-dn6yj4ti.authentication.ca10.hana.ondemand.com/oauth/token?grant_type=client_credentials" -u "sb-e0a3d792-09fd-42b7-8a2c-e4213af53411!b805|cas-uaa-prod!b58:J+neLeyi7wqBcEPXM1hl4CqAkTE=" --header 'content-type: application/json')" >> $GITHUB_OUTPUT
- 
-      - name: Check if token creation succeeded
+      - name: Check Token Creation Result
         run: |
-         if ! gh auth login --with-token curl GET --url "https://development-dn6yj4ti.authentication.ca10.hana.ondemand.com/oauth/token?grant_type=client_credentials" -u "sb-e0a3d792-09fd-42b7-8a2c-e4213af53411!b805|cas-uaa-prod!b58:J+neLeyi7wqBcEPXM1hl4CqAkTE=" --header 'content-type: application/json'; then
-            echo "Token creation failed: Bad credentials or insufficient permissions."
-            exit 1
-                
+          response=$(echo $response | jq -r '.access_token') # Assuming 'jq' is installed to parse JSON
+          if [ -n "$response" ]; then
+            echo "Token creation succeeded!"
+            echo "Token: $response"
+            # Proceed with other actions using the token
           else
-            echo "Token creation done!"
+            echo "Token creation failed!"
+            exit 1
           fi
+        env:
+          response: ${{ steps.runPostman.outputs.res }}
+     
       - name: Show Token
         run: |
           echo ${{ steps.runPostman.outputs.res}}
+          echo ${{ steps.runPostman.outputs.response }}
           
       - name: CAS
         id: casData
